### ISSUE TITLE
Styles are in conflict with tailwind styles

### ISSUE THREAD

**Issue by spjhon** [mevlutcantuna/react-beautiful-timeline#2]
provided styles conflict with tailwind styles, the .w-full{100%} is in conflict and if I deleted from the library the app works, but with that line of code and tailwind there are problems.

Another thing, how to center the vertical timeline?

**Comment by mevlutcantuna** [comment]
Hello @spjhon, 
I think you can add css style.Also If it is okay for you, you can open a PR. I will merge it.
